### ISSUE TITLE
Internet would enable itself right after disabling

### ISSUE THREAD

**Issue by PCTipsGR** [NeotiDev/iswitch#1]
I noticed some days ago a bug in my program, which enabled the internet connection back right after disabling it.

I wondered why this happened and went back to check my code, then realized that I had made a typo, and that I had forgot to add `goto END` to the end of the disabling section.

I already patched this in the master release and I will be releasing the new version of the software soon.

**Comment by PCTipsGR** [comment]
Until I fix this issue, you may download the master release and convert it yourself.

**Comment by yagizhan49** [comment]
Seems fixed. However @PCTipsGR will need to make a new release. You can still use the app by the .cmd file
